PLUGIN_NAME=            caddy-policy
PLUGIN_VERSION=         1.0
PLUGIN_COMMENT=         Caddy certificate authority policy for OPNsense images
PLUGIN_MAINTAINER=      ted.welch@biptec.com
PLUGIN_WWW=             https://github.com/biptec/opnsense-proxmox
PLUGIN_NO_ABI=          yes

PLUGINSDIR?=            /usr/plugins
.include "${PLUGINSDIR}/Mk/plugins.mk"
