PLUGIN_NAME=            nocloud-bootstrap
PLUGIN_VERSION=         1.2
PLUGIN_COMMENT=         NoCloud bootstrap integration for OPNsense virtual machines
PLUGIN_DEPENDS=         sudo
PLUGIN_MAINTAINER=      ted.welch@biptec.com
PLUGIN_WWW=             https://github.com/biptec/opnsense-proxmox
PLUGIN_NO_ABI=          yes

PLUGINSDIR?=            /usr/plugins
.include "${PLUGINSDIR}/Mk/plugins.mk"
